### ISSUE TITLE
Use more restrictive permissions

### ISSUE THREAD

**Issue by gregoryduckworth** [nearform/github-action-check-linked-issues#214]
Rather than use the open `GITHUB_TOKEN` with the ability to read/write to everything we should advise more restrictive permissions. We should update the documentation to match.

I believe the permissions should be:
```
permissions:
  contents: read
  issues: write
  pull-requests: write
```
